---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 5.3.2"
  - PUPPET_VERSION="~> 5.3.3"
  - PUPPET_VERSION="~> 5.3.4"
  - PUPPET_VERSION="~> 5.3.5"
  - PUPPET_VERSION="~> 5.3.6"
  - PUPPET_VERSION="~> 5.3.2" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 5.3.3" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 5.3.4" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 5.3.5" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 5.3.6" STRICT_VARIABLES=yes
matrix:
  exclude:
  # Ruby 1.9.3
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"

  # Ruby 2.0.0
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"

  # Ruby 2.1.0
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
